name: mangle
description: An absolute bare-bones web app.
author: jonahwilliams <jonahwilliams@google.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js:
  meta:
  angular_ast:
  build:

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
